### ISSUE TITLE
Duplicate definition of MODE_SLEEP, MODE_FORCE, MODE_NORMAL

### ISSUE THREAD

**Issue by jiinjoo** [akita11/Omron2SMPB02E#1]
Hello, in https://github.com/akita11/Omron2SMPB02E/blob/master/src/Omron2SMPB02E.h

MODE_SLEEP, MODE_FORCE, MODE_NORMAL are defined twice, and MODE_NORMAL is not the same

#define MODE_SLEEP  0
#define MODE_FORCE  1
#define MODE_NORMAL 2

// arg of set_mode()
#define MODE_SLEEP 0x0
#define MODE_FORCED 0x1
#define MODE_NORMAL 0x3

which is the correct MODE_NORMAL? 2 or 3?

**Comment by akita11** [comment]
According to datasheet, MODE_NORMAL is 0x03, not 2. I'll fix it on source code.
